### ISSUE TITLE
Connecition Failed Event

### ISSUE THREAD

**Issue by LumiProj** [vitalyster/SharpXMPP#97]
Hi,

I am looking to catch the ConnectionFailed Event but it does work as I expected.
I am using this library in my chat app using Xamarin Forms, It is working perfectly fine.
I noticed that when app at background for sometime so app disconnect from the xmpp server.
Now I wanted to know is there any way I can check the XmppClient connection state so that would help me see the connection state of the XmppClient to achieve the desired task.

Thanks

**Comment by vitalyster** [comment]
You can not use persistent networking connections in background on mobile phones at all:
1. You can not use XmppConnection on Android:
* Battery optimizations (Doze mode) will kill all background network connections without notice
* Many vendors have their own battery optimizations which kill background network connections even if you add your app to whitelist
2. You can not use XmppConnection on iOS:
* Background network connections are killed without notice by default
* You can request time to complete tasks (up to 10 minutes) but you still need to close connections in that period of time

So there is no reason to monitor XmppConnection state: it will work only in foreground. The only option to receive messages in background is push notifications

**Comment by AtifShahzed** [comment]
Hi,
Thank you for detail response, I must appreciate that.
Well you are absolutely right and I am dealing this behaviour with push notifications.
My question was if app goes into background so network connection kills automatically after few minutes and when user moves app into foreground so I wanted to reconnect to XMPP Server so is there any property or method is available to check the client XMPP connection so that would help to identify the connection state or the second approach is to reconnect the xmpp server straight away on app resume.


I hope you got my point.

Thanks! once again

**Comment by vitalyster** [comment]
You can send keep-alive pings (XEP-0199) on some interval to make sure you are alive or you will receive ConnectionFailed event
